apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  selector:
    matchLabels:
      app: spring-petclinic
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - image: harbor-01a.corp.tanzu/library/spring-petclinic:latest
        imagePullPolicy: Always
        name: spring-petclinic
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: spring-petclinic
